export const ADD_TO_CART_LOAD = "ADD_TO_CART_LOAD";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const GET_MY_CART_LOAD = "GET_MY_CART_LOAD";
export const GET_MY_CART_SUCCESS = "GET_MY_CART_SUCCESS";
export const GET_MY_CART_FAIL = "GET_MY_CART_FAIL";

export const DELETE_FROM_CART_LOAD = "DELETE_FROM_CART_LOAD";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_FAIL = "DELETE_FROM_CART_FAIL";
