export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_BYID_LOAD = "GET_PRODUCT_BYID_LOAD";
export const GET_PRODUCT_BYID_SUCCESS = "GET_PRODUCT_BYID_SUCCESS";
export const GET_PRODUCT_BYID_FAIL = "GET_PRODUCT_BYID_FAIL";

export const ADD_PRODUCT_LOAD = "ADD_PRODUCT_LOAD";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const DELETE_PRODUCT_LOAD = "DELETE_PRODUCT_LOAD";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const EDIT_PRODUCT_LOAD = "EDIT_PRODUCT_LOAD";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";

export const GET_MY_PRODUCTS_LOAD = "GET_MY_PRODUCTS_LOAD";
export const GET_MY_PRODUCTS_SUCCESS = "GET_MY_PRODUCTS_SUCCESS";
export const GET_MY_PRODUCTS_FAIL = "GET_MY_PRODUCTS_FAIL";
